fl=blinkingfluorophore;
fl.photonbudget=10000;
psfdonut=PSFMF_donut2D;
sim=AbberiorSimulator(fl);
numlocs=12;
fname='/Users/ries/Downloads/2Dtracking_L75nm_phtLimit1000_.json';
sim.loadsequence(fname)
sim.makepatterns
sim.runSequence